services:
  - type: web
    name: mm-cafe
    runtime: node
    plan: free
    buildCommand: npm run build && npm run migrate && npm run seed
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "8h"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://mm-cafe.onrender.com
